### ISSUE TITLE
Does not recognise on nvm uninstall

### ISSUE THREAD

**Issue by IniZio** [bahmutov/all-nvm#5]
I used the all-nvm with nvm, however after I uninstall a specific version such as 4.8.0, it still attempts to run for that version. How do I refresh the cache for all-nvm?

**Comment by bahmutov** [comment]
Hmm, I am using nvm-api method to find the installed versions seee https://github.com/btleffler/node-nvm-api/blob/master/index.js#L269
Not sure why this would fail.

**Comment by IniZio** [comment]
I attempted to remove .nvm/ and install again still no luck, might be a problem with nvm-api in fact

**Comment by bahmutov** [comment]
could be, I would open an issue with them

**Comment by IniZio** [comment]
Is an issue with nvm-api rather than all-nvm, closing.
